config/routes.rb
Rails.application.routes.draw do
  # REST :https://zh.wikipedia.org/wiki/%E8%A1%A8%E7%8E%B0%E5%B1%82%E7%8A%B6%E6%80%81%E8%BD%AC%E6%8D%A2
  resources :users, only: [:create] do
    collection do
      get :sign_up, action: 'new'
    end
  end

  resources :sessions, path: 'users', only: [] do
    collection do
      get :sign_in, action: 'new'
      post :sign_in, action: 'create'
      delete :sign_out, action: 'destroy'
    end
  end

  # // POST /restaurants/2/pocket_list
  resources :restaurants do
    member do
      post :pocket_list 
    end
    resources :comments, shallow: true, 
                         only: [:create, :destroy]
    # resources :comments, only: [:index, :new, :create]
  end
  # resources :comments, except: [:index, :new, :create]

  root "restaurants#index"

  # get '/restaurants', to: 'restaurants#index'
  #
  # get '/new_restaurant', to: 'restaurants#new'
  #
  # post '/restaurant_list', to: 'restaurants#list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite_restaurant.rb
class FavoriteRestaurant < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # 軟刪除
  acts_as_paranoid

  validates :title, presence: true
  belongs_to :user
  has_many :comments

  has_many :favorite_restaurants
  has_many :likers, through: :favorite_restaurants,
                           source: :user


  # default_scope { available }
  # scope :available, -> { where(deleted_at: nil) }
  #
  # # Restaurant.deleted
  # def self.deleted
  #   unscope(:where).where.not(deleted_at:nil)
  # end
  #
  # # 使用者方法
  # def destroy
  #   update(deleted_at: Time.now)
  # end
  #
  # # 管理員方法
  # def really_destroy!
  #   super.destroy
  # end
end

app/models/user.rb
  module Encryptor
    require 'digest'
    def self.encrypt(password)
      Digest::SHA1.hexdigest(password)
    end

    def self.salted(password, head = "123", tail = "xx")
      "#{head}#{password}#{tail}"
    end
  end

class User < ApplicationRecord
  validates :email, presence: true, 
                    uniqueness: true,
                    format: { with: /.+\@.+\..+/ }
  validates :password, presence: true,
                       confirmation: true

  before_create :encrypt_password

  has_many :restaurants # owner

  has_many :favorite_restaurants
  has_many :pocket_list, through: :favorite_restaurants, 
                           source: :restaurant

  has_many :comments

  def self.login(params)
    email = params[:email]
    password = params[:password]

    salted_password = Encryptor.salted(password)
    encrypted_password = Encryptor.encrypt(salted_password)

    find_by(email: email, password: encrypted_password)
  end

  def like?(restaurant)
    pocket_list.exists?(restaurant.id)
  end

  private
  def encrypt_password
    # 加密
    salted_pwd = Encryptor.salted(password)
    self.password = Encryptor.encrypt(salted_pwd) 
    # self.password = Digest::SHA1.hexdigest(password)
    # self.password = (Digest::SHA1.hexdigest(password))
    # password = Digest::SHA1.hexdigest(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  helper_method :current_user, :user_signed_in?

  private
   def not_found
     render file: "#{Rails.root}/public/404.html",
            status: 404
   end

   def current_user
     User.find_by(id: session[ENV['session_name']])
   end

   def user_signed_in?
     if session[ENV['session_name']]
       return true
     else
       return false
     end
   end

   def check_user!
     redirect_to root_path if not user_signed_in?
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_user!

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.new(comment_params)
    # @comment.user = current_user
    # @comment.ip_address = 抓ip

    if @comment.save
      # 執行 create.js.erb
      # 不做事
      # redirect_to restaurant_path(@restaurant) # 餐廳的show 標準
      # redirect_to @restaurant # 餐廳的show　簡寫
    else
      render 'restaurants/show'
    end
    # render html: params
  end

  def destroy
  end

  private
  def comment_params
    permited_params = params.require(:comment).permit(:content)
                                              .merge({user: current_user})
    # permited_params = params.require(:comment).permit(:content).merge({user: current_user, ip_address: ....})
    # permited_params = params.require(:comment).permit(:content)
    # permited_params[:user] = current_user
    # return permited_params
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:edit, :update, :destroy]
  # before_action :find_restaurant, except: [:index, :new, :create]
  before_action :check_user!, except: [:index, :show]
  # skip_before_action :verify_authenticity_token

 def index
   @restaurants = Restaurant.all.includes(:user, :likers)
 end

 def show
   @restaurant = Restaurant.find(params[:id]) 
   # @comment = Comment.new # 全新什麼都沒有
   @comment = @restaurant.comments.new # 全新的，直接把餐廳id代入
   @comments = @restaurant.comments.order(id: :desc)
 end

 def pocket_list
   @restaurant = Restaurant.find(params[:id]) 

   # if (current_user.pocket_list.exists?(@restaurant.id))

   if (current_user.like?(@restaurant))
     # 移除名單
     current_user.pocket_list.destroy(@restaurant)
     render json: { id: @restaurant.id, status: 'removed'}
   else
     # 加名單
     current_user.pocket_list << @restaurant
     render json: { id: @restaurant.id, status: 'added'}
   end
   # render json: params
 end

 def new
   @restaurant = Restaurant.new
 end

 def create
   # @restaurant = Restaurant.new(restaurant_params)
   # @restaurant.user_id = current_user.id

   # @restaurant = Restaurant.new(restaurant_params)
   # @restaurant.user = current_user
   @restaurant = current_user.restaurants.new(restaurant_params)
   
   if @restaurant.save
     redirect_to restaurants_path, notice: '餐廳成功建立'
   else
     render :new # 借new.html.erb
   end
 end

 def edit
   # @restaurant = Restaurant.find(params[:id]) # 只能找id
 end

 def update
   # @restaurant = Restaurant.find(params[:id]) # 只能找id

   if @restaurant.update(restaurant_params)
     # flash[:nitice] = 'good!'
     redirect_to restaurant_path(@restaurant), notice: '成功修改資料!'
   else
     render :edit
   end
 end

 def destroy
   # @restaurant = Restaurant.find(params[:id])
   @restaurant.destroy
   redirect_to restaurants_path, notice: '成功修改資料!'
 end

 private
   # authentication 指允許可以進來這個大門，代表有認證。 但不能進去。 (驗證)
   # authorization 有沒有授權，可不可以做這件事情。                   (授權)
   # 1
   def find_restaurant
     # @restaurant = Restaurant.find(params[:id]) 
     # @restaurant = Restaurant.find_by!(
     #   id: params[:id],
     #   user_id: current_user:id
     # )
   # 2
     @restaurant = current_user.restaurants.find(params[:id])
   end

   def restaurant_params
     params.require(:restaurant).permit(:title, :tel, :address, :email, :description)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.login(user_params)
    if user
      # 發號碼牌
      session[ENV['session_name']] = user.id
      # 轉去首頁
     redirect_to root_path
    else
     redirect_to sign_in_sessions_path 
    end

    # render html: params
    # 1 查有無帳號 / 密碼
    # 2 轉址 / 重登
  end

  def destroy
    # 撕票
    session[ENV['session_name']] = nil
    # 轉址
     redirect_to root_path
  end

private
def user_params
  params.require(:user).permit(:email, :password)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new 
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
// alert('你輸入了：<%= @comment.content %>')

var area = document.querySelector('#comment_area')
var li = document.createElement('li')
li.textContent = '<%= @comment.content %>'
area.prepend(li)
document.querySelector('#comment_content').value = ''
// console.log(area)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uchef</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' if notice %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@restaurant) do |f| %>
<div class="field">
  <%= f.label :title %>  
  <%= f.text_field :title, placeholder: '請輸入餐廳名稱' %>
</div>

<div class="field">
  <%= f.label :tel %>
  <%= f.text_field :tel, placeholder: '請輸入電話號碼' %>
</div>

<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: '請輸入Email信箱' %>
</div>

<div class="field">
  <%= f.label :address %>
  <%= f.text_field :address, placeholder: '請輸入您的住址' %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: '請輸入您對此餐廳的描述' %>
</div>

<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>編輯餐廳</h1>

  <%= render 'form' %>

  <%# # partial render 局部渲染 %>

app/views/restaurants/index.html.erb
<h1 class="bg-red-300">餐廳列表</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li>
    <%= link_to restaurant.title, restaurant_path(restaurant) %>  
    (
      <%= restaurant.user.email %>
      <%= restaurant.likers.count %>
    )
    <%= link_to "編輯", edit_restaurant_path(restaurant) %>
    <%#= link_to "刪除", restaurant_path(restaurant), 'data-method': 'delete', 'data-confirm': '確定要刪除嗎？' %>
    <%#= link_to "刪除", 
                     restaurant_path(restaurant),
                     data: { method: 'delete',
                      confirm: '確定要刪除嗎？'} %>
    <%= link_to "刪除", 
                 restaurant_path(restaurant),
                 method: 'delete',
                 data: { confirm: '確定要刪除嗎？'} %>
    <%#= link_to "刪除", restaurant_path(restaurant), method: 'delete' %>
  </li>
<% end %>
</ul>




<%= link_to '新增餐廳', new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1>新增餐廳</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%# # partial render 局部渲染 %>

app/views/restaurants/show.html.erb
<h1 data-controller="pocket">
  <%= @restaurant.title %>
  <div id="like-btn" 
       data-action="click->pocket#add" 
       data-pocket-target="btn"
       data-id="<%= @restaurant.id %>" 
       class="like-btn <%= 'like-btn-favorited' if user_signed_in? && current_user.like?(@restaurant) %>">
  </div>
</h1>

<h3>留言</h3>
<%# # POST /comments

<%# <%= form_with(model: @comment, url: restaurant_comments_path(@restaurant)) do |form| %>
<%#   <div class ="field">
<%#     <%= form.label :content, '留言內容 with' %>
<%#     <%= form.text_area :content %>
<%#   </div>  
<%#   <%= form.submit %>
<%# <% end %>

<%= form_for(@comment, url: restaurant_comments_path(@restaurant),remote: true) do |form| %>
  <div class ="field">
    <%= form.label :content, '留言內容 for' %>
    <%= form.text_area :content %>
  </div>  
  <%= form.submit %>
<% end %>

<ul id="comment_area">
<% @comments.each do |comment| %>
  <li><%= comment.content %></li>
<% end %>
</ul>

<%= link_to '返回餐廳列表', restaurants_path %>

app/views/shared/_flash.html.erb
<div class="flash" data-controller="flash">
  
  <span>
    <%= notice %>
  </span>
  
  <button data-action="flash#close">
    <i class="fas fa-times-circle close"></i>
  </button>
</div>

app/views/shared/_navbar.html.erb
<section class="text-right py-2 pr-2">
  <% if user_signed_in? %>
    <i class="fas fa-user-astronaut"></i>
    <%= current_user.email %> |
    <%= link_to '登出', sign_out_sessions_path, method: 'delete' %>
  <% else %>
    <%= link_to '註冊', sign_up_users_path %> | 
    <%= link_to '登入', sign_in_sessions_path %> 
  <% end %>
</section>

app/views/users/new.html.erb
<h1> 註冊帳號 </h1>

<%= form_for(@user) do |form| %>
  
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: '請輸入信箱' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: '請輸入密碼' %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, placeholder: '請輸入確認密碼' %>
  </div>
  
  <%= form.submit "註冊" %>
<% end %>